model_id: sam3_vit_h
display_name: "SAM 3 ViT-H ONNX (GPU)"
batch_processing_mode: "text_prompt"
params: {}
widgets:
  - {name: edit_text, value: null}
  - {name: button_send, value: null}
  - {name: add_pos_rect, value: null}
  - {name: add_neg_rect, value: null}
  - {name: button_run_rect, value: null}
  - {name: button_clear, value: null}
  - {name: button_finish_object, value: null}
  - {name: input_conf, value: null}
  - {name: edit_conf, value: 0.50}
  - {name: mask_fineness_slider, value: 10}
  - {name: mask_fineness_value_label, value: null}
  - {name: toggle_preserve_existing_annotations, value: false}
